custom: "I am a custom string included via yaml."
test: Default File
gems:
 - jekyll-sitemap
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
